### ISSUE TITLE
Memcache instalation

### ISSUE THREAD

**Issue by philipnorton42** [hashbangcode/vlad#12]
Hi,

any particular reason, why memache is not installed like this?

```
#!yaml

---
- name: install packages
  apt: pkg={{ item }} state=installed
  sudo: true
  with_items:
    - memcached
    - php5-memcache
  notify:
    - restart apache2

```

Current playbook will fail during second provision run, because pecl instalation. 

---
- Bitbucket: https://bitbucket.org/philipnorton42/vlad/issue/12
- Originally Reported By: [Ján Koščo](http://bitbucket.org/s7anley)
- Originally Created At: 2014-03-07T14:26:04.926
