### ISSUE TITLE
my.cnf values being overidden

### ISSUE THREAD

**Issue by sgrichards** [hashbangcode/vlad#125]
When I provision a new box the max_packets value for example is still set to the default (16mb) rather than the value indicated in the settings.yml

As far as I can tell the current file that the mysql settings are being written to is being overridden by other my.cnf files.

```
# set up mysql variables
- name: create MySQL configuration file
  action: template src=debian_mysql.my.cnf.j2 dest=/etc/my.cnf
  sudo: true
  notify: 
  - restart mysql
```

My understanding is that my.cnf files are loaded in the following order:

/etc/my.cnf
/etc/mysql/my.cnf
/usr/etc/my.cnf
~/.my.cnf

...or am i missing something incredibly obvious - apologies if that is the case!

_FYI: using ubuntu 14 but saw the same on ubuntu 12_
