### ISSUE TITLE
Error when using npm

### ISSUE THREAD

**Issue by danbohea** [hashbangcode/vlad#223]
Trying to do anything with npm within the guest box results in:

```
Error: ENOENT, stat '/home/vagrant/.node'
```

This appears to be something to do with the tail end of the node role (line 25 onward of node.yml):

```
- name: set local node prefix
  template: src=npmrc.j2 dest=/home/{{ user }}/.npmrc

- name: set local node path in bash profile
  lineinfile:
    dest: /home/{{ user }}/.bashrc
    line: 'export PATH=$HOME/.node/bin:$PATH'
    state: present
```
