### ISSUE TITLE
Task Privilege Escalation replacing 'sudo:yes'

### ISSUE THREAD

**Issue by philipnorton42** [hashbangcode/vlad#240]
Version 1.9 of Ansible has introduced the become parameter:
http://docs.ansible.com/become.html

This means that we should move from this:

```
- name: install apache2 packages
  yum: pkg={{ item }} state=installed
  with_items:
   - httpd
   - httpd-devel
  sudo: true
```

To using the new 'become' syntax.

```
- name: install apache2 packages
  yum: pkg={{ item }} state=installed
  with_items:
   - httpd
   - httpd-devel
  become: sudo
```

Not an immediate change, but this should be on our roadmap.
