### ISSUE TITLE
drush7 and drush-master aliases aren't working

### ISSUE THREAD

**Issue by wizonesolutions** [hashbangcode/vlad#280]
````yaml
---
#  _________________________
# < Vlad configuration file >
#  -------------------------
#         \   ^__^
#          \  (oo)\_______
#             (__)\       )\/\
#                 ||----w |
#                 ||     ||
#
# Change settings here to control how Vlad sets up your box.
#
# See the full list of available variables here.
# http://vlad-docs.readthedocs.org/en/latest/usage/variables/
#
  
# Webserver settings
  webserver_hostname: 'd86.fillpdf.io'
  webserver_hostname_aliases: 
  - 'www.d86.fillpdf.io'

# Vagrantfile configuration
  boxipaddress: "192.168.102.100"
  boxname: "fpd8"
  host_synced_folder: "../docroot"
# or on Windows
#  host_synced_folder: "C:\\docroot"

# Install components:
# - To install a component set it to true.
# - To leave a component out of the install set the value to false.

  adminer_install: true

  apache_install: true

  imagemagick_install: false

  mailcatcher_install: false

  memcached_install: false

  munin_install: false

  mysql_install: true

  node_install: false

  php_install: true

  pimpmylog_install: false

  redis_install: false

  ruby_install: false # Ruby is required by MailCatcher

  sendmail_install: false

  solr_install: false

  varnish_install: false # If you turn this off then make sure you set the http_port to be 80.

  xhprof_install: false

# HTTP port for the web server. If you choose to install Varnish then you might want to set this to "8080"
  http_port: 80

# HTTP port for the Varnish cache
  varnish_http_port: 80

  parallels_update_guest_tools: true

  db_import_up: true

  drush_version: master
````

````
Vagrant 1.7.4
ansible 1.9.3
  configured module search path = None
protobox (0.0.2)
vagrant-berkshelf (4.0.4)
  - Version Constraint: >=2.0.1
vagrant-cachier (1.2.1)
vagrant-digitalocean (0.7.7)
vagrant-hostmanager (1.6.1)
vagrant-hostsupdater (0.0.11)
vagrant-omnibus (1.4.1)
vagrant-parallels (1.4.1)
vagrant-protobox (0.0.2)
vagrant-share (1.1.4, system)
vagrant-triggers (0.5.1)
vagrant-vbguest (0.10.0)
````

````
 fpd8 ✝ /var/www/site/docroot $ drush7
No command 'drush7' found, did you mean:
 Command 'drush' from package 'drush' (universe)
drush7: command not found
✝ fpd8 ✝ /var/www/site/docroot $ drush-master
drush-master: command not found
````

What's wrong with my setup? Even setting `drush_version` to `master` didn't do the trick.
