### ISSUE TITLE
DISCUSSION: Streamline configuration of settings.php

### ISSUE THREAD

**Issue by wizonesolutions** [hashbangcode/vlad#293]
I'm noticing a pattern in a team I work with and that I'm trying to get on Vlad; Vlad is so easy that they forget about the specific "last-mile" site configuration that we need, e.g. `local.settings.php` or similar for Pantheon.

That said, I'm wondering if we could build a template into Vlad that would generate a `settings.php` file and include basic configuration. I wanted to discuss the idea first.

My basic thoughts are:

- This would be turned off by default.

- Config-wise:

````yaml
# Whether to generate settings.local.php or not. Doing so can be useful if you're on a provider, such as Pantheon or Acquia Cloud, that expects you to commit settings.php to your codebase.
vlad_generate_local_settings: false

# The name of the local settings file to generate.
vlad_local_settings_filename: settings.local.php

# Whether Vlad should continue to keep the local settings file updated. Leave this false to have Vlad only generate a local settings file when one does not already exist.
# NOTE: Having this on will overwrite any changes you make when you run `vagrant provision`!
vlad_manage_local_settings: false

# If you would like to use a custom local settings template for this site, enter the path to an Ansible template that can be used to generate the file. It's recommended that you copy <THE DEFAULT LOCAL SETTINGS TEMPLATE> and tweak it to your needs.
vlad_local_settings_template_path: ''
````

I chose `settings.local.php` as the default because IIRC this is the pattern that the core `.gitignore` uses to ignore all settings files.

When Vlad manages the settings file, it would simply include database information. I figure we can probably just generate `$db_url` AND `$databases` (in that order), such that Drupal 6 and 7 pick up the one they understand. Drupal 8 looks like it works with Drupal 7's syntax as well.

A future idea is another parameter where they specify the Drupal version and we generate a settings file appropriate for it. But the main objective of this feature is to require less of end users and let the ones who know how to set up the site package it up more easily for the rest.

Interested in your thoughts. It's kind of a feature request in that I don't know if I'll be developing it soon, just noticed the need.
