### ISSUE TITLE
Allow for additional synced directories

### ISSUE THREAD

**Issue by mlander** [hashbangcode/vlad#313]
In Drupal 8, I think you'll see more dependencies and scripts living outside of docroot, particularly when installed via composer(i.e. https://github.com/drupal-composer/drupal-project). 

A directory may end up looking like:
docroot -> ./web
scripts
vendor
vlad
vlad_aux
web

I think minimum, having the 'vendor' directory would suffice, but perhaps allowing for an array of values?  I'm not sure how much of a performance hit it would be to have additional synced directories?

**Comment by danbohea** [comment]
I'm all for this providing it's developed with #253 in mind.

**Comment by zxaos** [comment]
I've got a custom play that handles this exact format currently. Note you might need to change the paths, as I'm also installing vlad through composer in the scenario:

relevant part of vlad_settings:
```yaml
  host_synced_folder: "../../.."
  aux_synced_folder: "../../../vlad_aux"

# Change the docroot to match what composer builds while we wait for vlad
# issue #284
  vlad_custom_play: true
  vlad_custom_play_path: "../../../vlad_custom"
  webserver_custom_docroot: 'web'

# Tweaks
  add_index_file: false
```

vlad_custom play:
```yaml
---
- hosts: all
  user: vagrant
  vars_files:
    - "../vendor/hashbangcode/vlad/vlad_guts/merged_user_settings.yml"


  tasks:
    - name: adjust composerified drupal docroot
      sudo: true
      lineinfile:
        name=/etc/apache2/sites-available/{{ webserver_hostname }}.conf
        line="  DocumentRoot /var/www/site/docroot/{{ webserver_custom_docroot }}"
        regexp="\w*DocumentRoot /var/www/site/docroot"
        state=present
      notify:
        - restart apache2
    - name: adjust composerified drupal vhost directory
      sudo: true
      lineinfile:
        name=/etc/apache2/sites-available/{{ webserver_hostname }}.conf
        line="  <Directory /var/www/site/docroot/{{ webserver_custom_docroot }}>"
        regexp="\w*<Directory /var/www/site/docroot.*"
        state=present
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
      sudo: true

    - name: restart httpd
      service: name=httpd state=restarted
      sudo: true
```
