### ISSUE TITLE
php | install php packages results in WARNING: The following packages cannot be authenticated!

### ISSUE THREAD

**Issue by wizonesolutions** [hashbangcode/vlad#323]
I'm going to try a Bento box, but figured I'd report this:

Error information:
````
TASK: [php | install php packages] ********************************************
failed: [192.168.115.100] => (item=php5,php5-cli,php5-common,php5-dev,php5-gd,php5-gmp,php5-mysql,php5-xmlrpc,php-soap,php5-curl,php5-mcrypt,php-apc,php-pear) => {"failed": tru
e, "item": "php5,php5-cli,php5-common,php5-dev,php5-gd,php5-gmp,php5-mysql,php5-xmlrpc,php-soap,php5-curl,php5-mcrypt,php-apc,php-pear"}
stderr: E: There are problems and -y was used without --force-yes

stdout: Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  autoconf automake autotools-dev debhelper dh-apparmor dh-php5
  fontconfig-config fonts-dejavu-core gettext intltool-debian
  libapache2-mod-php5 libasprintf-dev libcroco3 libfontconfig1 libgd3
  libgettextpo-dev libgettextpo0 libjbig0 libjpeg-turbo8 libjpeg8 libltdl-dev
  libltdl7 libmail-sendmail-perl libmcrypt4 libmysqlclient18 libonig2
  libpcre3-dev libpcrecpp0 libqdbm14 libsigsegv2 libsys-hostname-long-perl
  libtiff5 libtool libunistring0 libvpx1 libx11-6 libx11-data libxcb1 libxpm4
  m4 mysql-common php-auth-sasl php-http-request php-mail php-mail-mime
  php-net-dime php-net-smtp php-net-socket php-net-url php5-apcu php5-json
  php5-readline pkg-php-tools po-debconf shtool
Suggested packages:
  autoconf2.13 autoconf-archive gnu-standards autoconf-doc dh-make
  apparmor-easyprof gettext-doc libgd-tools libtool-doc libmcrypt-dev mcrypt
  apparmor-easyprof gettext-doc libgd-tools libtool-doc libmcrypt-dev mcrypt
  automaken gfortran fortran95-compiler gcj-jdk php5-user-cache
  libmail-box-perl
The following NEW packages will be installed:
  autoconf automake autotools-dev debhelper dh-apparmor dh-php5
  fontconfig-config fonts-dejavu-core gettext intltool-debian
  libapache2-mod-php5 libasprintf-dev libcroco3 libfontconfig1 libgd3
  libgettextpo-dev libgettextpo0 libjbig0 libjpeg-turbo8 libjpeg8 libltdl-dev
  libltdl7 libmail-sendmail-perl libmcrypt4 libmysqlclient18 libonig2
  libpcre3-dev libpcrecpp0 libqdbm14 libsigsegv2 libsys-hostname-long-perl
  libtiff5 libtool libunistring0 libvpx1 libx11-6 libx11-data libxcb1 libxpm4
  m4 mysql-common php-apc php-auth-sasl php-http-request php-mail
  php-mail-mime php-net-dime php-net-smtp php-net-socket php-net-url php-pear
  php-soap php5 php5-apcu php5-cli php5-common php5-curl php5-dev php5-gd
  php5-gmp php5-json php5-mcrypt php5-mysql php5-readline php5-xmlrpc
  pkg-php-tools po-debconf shtool
0 upgraded, 68 newly installed, 0 to remove and 45 not upgraded.
Need to get 117 kB/14.1 MB of archives.
After this operation, 60.6 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  fontconfig-config libfontconfig1 libjbig0 libtiff5 libgd3 libgettextpo0
  mysql-common libmysqlclient18 libpcrecpp0 php5-common php5-json php5-cli
  php-pear php5-curl php5-gd php5-gmp php5-mcrypt php5-mysql php5-readline
  php5-xmlrpc gettext dh-apparmor libapache2-mod-php5 libasprintf-dev
  libgettextpo-dev libpcre3-dev php5 php5-apcu php5-dev dh-php5 php-apc
  pkg-php-tools

msg: '/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold"   install 'php5' 'php5-cli' 'php5-common' 'php5-dev' 'php5-gd' 'php5-gmp' 'p
hp5-mysql' 'php5-xmlrpc' 'php-soap' 'php5-curl' 'php5-mcrypt' 'php-apc' 'php-pear'' failed: E: There are problems and -y was used without --force-yes


FATAL: all hosts have already failed -- aborting
````

`vlad_settings.yml`:

````yaml
---
#  _________________________
# < Vlad configuration file >
#  -------------------------
#         \   ^__^
#          \  (oo)\_______
#             (__)\       )\/\
#                 ||----w |
#                 ||     ||
#
# Change settings here to control how Vlad sets up your box.
#
# See the full list of available variables here.
# http://vlad-docs.readthedocs.org/en/latest/usage/variables/
#

# Webserver settings
  webserver_hostname: 'fillpdf-local7.io'
  webserver_hostname_aliases:
  - 'www.fillpdf-local7.io'
#  - 'www.example.com'

# Vagrantfile configuration
  boxipaddress: "192.168.115.100"
  boxname: "d7fillpdf"
  host_synced_folder: "../docroot"
  aux_synced_folder: "../vlad_aux"
# or on Windows
#  host_synced_folder: "C:\\docroot"

# Install components:
# - To install a component set it to true.
# - To leave a component out of the install set the value to false.

  adminer_install: true

  apache_install: true

  imagemagick_install: false

  mailcatcher_install: false

  memcached_install: false

  munin_install: false

  mysql_install: true

  node_install: false

  php_install: true

  pimpmylog_install: false

  redis_install: false

  ruby_install: false # Ruby is required by MailCatcher

  sendmail_install: false

  solr_install: false

  varnish_install: false # If you turn this off then make sure you set the http_port to be 80.

  xhprof_install: false

# Additional Drush modules
# The Coder and Site Audit commands will be installed by default, but you can override this list below.
#  drush_install_commands:
#    - { name: 'coder', version: ''}
#    - { name: 'registry_rebuild', version: ''}
#    - { name: 'site_audit', version: ''}

# HTTP port for the web server. If you choose to install Varnish then you might want to set this to "8080"
  http_port: 80

# HTTP port for the Varnish cache
  varnish_http_port: 80

  db_import_up: true
  dbname: ['vladdb', 'drupal6']

  parallels_update_guest_tools: true
````
