### ISSUE TITLE
Hostname error on vagrant up

### ISSUE THREAD

**Issue by Benjen** [hashbangcode/vlad#337]
I am provisioning a new site.  I downloaded latest version of vlad (1.1.6) and extracted it.  I renamed examples.vlad_settings.yml and updated accordingly.  When I run vagrant up, it fails with the following error:

> There are errors in the configuration of this machine. Please fix the following errors and try again:
> 
> vm:
> * The hostname set for the VM should only contain letters, numbers, hyphens or dots. It cannot start with a hyphen or dot.

I have looked at the settings file, but can't seem to locate the offending line:

```
# Webserver settings
  webserver_hostname: 'd8bootstrap.local'
  webserver_hostname_aliases: 
  - 'www.d8bootstrap.local'
#  - 'www.example.com'

# Vagrantfile configuration
  boxipaddress: "192.168.112.110"
  boxname: “d8bootstrap”
  host_synced_folder: "./docroot"
# or on Windows
#  host_synced_folder: "C:\\docroot"

# Install components:
# - To install a component set it to true.
# - To leave a component out of the install set the value to false.

  adminer_install: true

  apache_install: true

  imagemagick_install: false

  mailcatcher_install: false

  memcached_install: false

  munin_install: false

  mysql_install: true

  node_install: true

  php_install: true

  pimpmylog_install: false

  redis_install: false

  ruby_install: true # Ruby is required by MailCatcher

  sendmail_install: true

  solr_install: false

  varnish_install: false # If you turn this off then make sure you set the http_port to be 80.

  xhprof_install: false

# HTTP port for the web server. If you choose to install Varnish then you might want to set this to "8080"
  http_port: 80

# HTTP port for the Varnish cache
  varnish_http_port: 80
```
