### ISSUE TITLE
Add Selenium server so it can be run from the box

### ISSUE THREAD

**Issue by philipnorton42** [hashbangcode/vlad#54]
On my Vlad box I run selenium headless like this:

```
#!bash

sudo apt-get install openjdk-7-jre-headless
sudo apt-get install firefox
sudo apt-get install xvfb

wget http://selenium-release.storage.googleapis.com/2.40/selenium-server-standalone-2.40.0.jar
DISPLAY=:1 xvfb-run java -jar selenium-server-standalone-2.40.0.jar

```

Then I can run Behat tests with the @javascript tag. It would be great if Selenium was preinstalled and ready to use on Vlad instead of this manual setup.

---------------------------------------
- Bitbucket: https://bitbucket.org/philipnorton42/vlad/issue/54
- Originally Reported By: [Lars Olesen](http://bitbucket.org/lsolesen)
- Originally Created At: 2014-06-04T13:45:13.714

**Comment by wizonesolutions** [comment]
I'd like to revisit this. Here is my custom playbook that does this:

````yaml
---
- name: install behat prereqs
  hosts: all
  user: vagrant
  sudo: yes
  roles:
    - arknoll.selenium

- name: add behat to project if composer.json exists
  hosts: all
  user: vagrant
  tasks:
    - name: composer require drupal/drupal-extension
      composer:
        command: require
        arguments: "drupal/drupal-extension"
        working_dir: /var/www/site/docroot
````

(I haven't tested the `composer require` part, so it's likely not perfect. I just wanted everything done for me if I had to rebuild the box.)

Testing if Behat works now...will report back.
